language: go
go:
- 1.6
script:
  - GOOS=windows GOARCH=386 go build -o docker-webhook-windows-386.exe
  - GOOS=windows GOARCH=amd64 go build -o docker-webhook-windows-amd64.exe
  - GOOS=linux GOARCH=386 go build -o docker-webhook-linux-386
  - GOOS=linux GOARCH=amd64 go build -o docker-webhook-linux-amd64
deploy:
  provider: releases
  api_key:
    secure: gFyhU/9DBfpSyG2YXUP6Up6YcYFkYsIyoawvc9XEiap0Dh4pH6jAPpBtt6DEQ9QNy9lNtesl1qcsbHhq/ez/unBEVib7+QcghrWfuGpr0tJB15b1qmmoSIvHRgyLCVGqnkjJT96U9zLxd6UOuSkXPDXMwgsYDMRwfkaeTdYRmJmaxno5k5694/38d0JMLSEFvoNjtSd1wLtuCNq+ZhG/ceKNnEqTzikqi1rWZrR+zIgLHSSnXpqJ2Oh7VOAEA3blrttGKyaaFUBYFVangbgMXhMvonpiUR2rQUxAOZhnSrbq0CsTmFbsemxpG3mX1Dhx3e7YeLkb0IEj//RyNqoOwQ7O6ZL7fEYzil/6vv6f7kOTszkotIm5VuBk9W6GsZB/j3TQ+MF/iBJhKflEzVo/4ASr+jkyEedyXNP1zXPFJl5H2uM3/mCusbe/tRFn6D8AYUvlNOCgzzNDqHELqfBhR9sOf7JIetFwyDEbHuWcisbLws6vO9mljEsFOBRKwx4t3zzNX3cRI3p+9O0Y4BYVtb5e4mlI+upCL3aLgiIbjvpXVhf4jx3jcQ3fR4M5V/aDIGI1hFvS7/COzv4tvhKRZ6IsE/LJ/ZB1uI4A4f+VtBRmyxHlL4n7gLydmWMy5FQe3/LJ4ye5psh8LGSmVjWCwuVto/xK0AblTidwhza66X4=
  file:
    - "docker-webhook-windows-386.exe"
    - "docker-webhook-windows-amd64.exe"
    - "docker-webhook-linux-386"
    - "docker-webhook-linux-amd64"
  on:
    repo: TF2Stadium/docker-webhook-deploy
